# .prettierrc or .prettierrc.yaml
trailingComma: "es5"
tabWidth: 4
semi: false
singleQuote: true
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "avoid"
endOfLine: "lf"
printWidth: 80
useTabs: true
